### ISSUE TITLE
NetworkPrinter instance has no attribute '_Generic__write'

### ISSUE THREAD

**Issue by prashantam** [shantanubhadoria/python-printer-escpos#1]
NetworkPrinter instance has no attribute '_Generic__write'

**Comment by scriptingislife** [comment]
I get the same error with the USBPrinter class.

**Comment by mnotgninnep** [comment]
Same here:

> from escpos.connections import getUSBPrinter
> 
> printer = getUSBPrinter()(idVendor=0x04b8,  # USB vendor and product Ids for EPSON TM-T88III
>                           idProduct=0x0202,  # printer
>                           inputEndPoint=0x82,
>                           outputEndPoint=0x01)
> 
> printer.text("Hello World")
> printer.lf()

produces

> Traceback (most recent call last):
>   File "printhelloworld.py", line 7, in <module>
>     outputEndPoint=0x01)
>   File "/usr/local/lib/python3.4/dist-packages/escpos/connections.py", line 89, in __init__
>     self.initialize()
>   File "/usr/local/lib/python3.4/dist-packages/escpos/commandset/generic.py", line 463, in initialize
>     self.__write(self.__class__.__ESC + '@')
> AttributeError: 'USBPrinter' object has no attribute '_Generic__write'

**Comment by mnotgninnep** [comment]
Further investigation, same behaviour in Python 2.7.9 and 3.4.2.

/usr/local/lib/python2.7/dist-packages/escpos/commandset/generic.pyc is the only occurrence of the offending attribute.

>  R^Q^@^@^@R^R^@^@^@R^S^@^@^@R^T^@^@^@s1^@^@^@align must be 'left', 'center', 'right' or 'full'R^F^@^@^@N(^D^@^@^@s^D^@^@^@lefts^F^@^@^@centerR^S^@^@^@R^T^@^@^@($
> ^@^@^@ValueErrort^O^@^@^@_Generic__writet       ^@^@^@__class__t
> ^@^@^@_Generic__ESCt^R^@^@^@_Generic__alignMap(^B^@^@^@R ^@^@^@t^E^@^@^@align(^@^@^@^@(^@^@^@^@sC^@^@^@

Here is what I believe is the same snippet from /usr/local/lib/python2.7/dist-packages/escpos/commandset/generic.py

>  raise ValueError('align must be \'left\', \'center\', \'right\' or \'full\'')
>         else:
>             self.__write(self.__class__.__ESC + 'a' + self.__class__.__alignMap[align])

Deleting the pyc files causes them to be recreated the same when the script it run again.
Not sure why Python mashes it when compiling this but I don't know enough to get any further.

**Comment by shantanubhadoria** [comment]
Sorry I have been a little busy(Moving to another country and job). However if you could send a pull request with a fix I would be happy to merge and release. I will ultimately get around to fixing this anyway. 
Cheers!

**Comment by jay-parikh** [comment]
@shantanubhadoria 
Getting same issue. Any fix for this?
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/escpos/connections.py", line 89, in __init__
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/escpos/commandset/generic.py", line 463, in initialize
    self.__write(self.__class__.__ESC + '@')
AttributeError: USBPrinter instance has no attribute '_Generic__write'
`

**Comment by krisjanis-gross** [comment]
Tried this on latest raspbian. Getting the same issue.

**Comment by shantanubhadoria** [comment]
Hi guys,
I have been a little occupied with the paid work at the moment. 
However if someone can make a quick pull request on this I will be happy to pull it in and make a release. If that doesn't happen I will ultimately get around to fixing this.
Cheers

**Comment by GreatestPython** [comment]
When will this been fixed? Thanks in advance.

**Comment by jonalxh** [comment]
Same error here

**Comment by mnotgninnep** [comment]
Sorry I meant to post back in the end. I did find a solution that worked on my raspberry pi but not to this particular module. I used the similar project python-escpos.

**Comment by afzal415** [comment]
Same error , has this issue been fixed

**Comment by shtefanilie** [comment]
Hi, any news on this issue? has It been fixed?

**Comment by joeldesante** [comment]
Has this issue been fixed?

**Comment by encode1** [comment]
Thanks @iliis,  Fix works, lets kindly merge into the master branch.

**Comment by fhavellant** [comment]
Can someone give me some help how i can pu the fix to my PI?
I am not sure how to install them?

**Comment by iliis** [comment]
> 
> 
> Can someone give me some help how i can pu the fix to my PI?
> I am not sure how to install them?

What's a PI? You can clone my repo instead: https://github.com/iliis/python-printer-escpos

**Comment by fhavellant** [comment]
i mean on my repro. Cloning is not an issue. i did this already.
But i don't know how to install it to have it running in phyton. I am using an raspberry

**Comment by iliis** [comment]
You can install from git using `pip install git+https://github.com/iliis/python-printer-escpos`

But I don't think this is really the right place for such general support questions.

**Comment by Koshelevzz** [comment]
> You can install from git using `pip install git+https://github.com/iliis/python-printer-escpos`

nope. 
 Running command git clone -q https://github.com/iliis/python-printer-escpos /tmp/pip-req-build-0xyvccs1
ERROR: File "setup.py" or "setup.cfg" not found for legacy project git+https://github.com/iliis/python-printer-escpos.

**Comment by shantanubhadoria** [comment]
Thank you for your patience everyone, I have merged this into the main branch! Thanks for the pull request @iliis
